import type { Metadata } from "next"
import { Roboto, Montserrat } from "next/font/google"
import "./globals.css"
import { Header } from "../components/Header"
import { Providers } from "@/components/Providers"

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "My Monney",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} dark ${roboto.className} antialiased`}
      >
        <Providers>
          <div className="p-8">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
